### ISSUE TITLE
v2 markdown file has a problem ... houston

### ISSUE THREAD

**Issue by compleatang** [waypointnda/waypointnda.com#12]
![screenshot-github com-2019 10 03-16_18_00](https://user-images.githubusercontent.com/590037/66140116-755a9980-e5f9-11e9-9b62-df416ec97ad8.png)

**Comment by kemitchell** [comment]
So apparently the Makefile configuration for building Markdown files went haywire.

I am actually inclined to stop generating Markdown automatically, and use the [type.commonform.org](https://type.commonform.org) syntax instead, manually. That Markdown would _not_ include signature pages or the standard form certificate, but would cover all the legal terms.

Thoughts?

**Comment by compleatang** [comment]
That would work perfectly for our purposes. As things currently sit we turn the docx into Markdown and remove the signature pages because https://github.com/monax/commonform-grpc adds them for us.
