### ISSUE TITLE
Bribery Act 2010

### ISSUE THREAD

**Issue by kemitchell** [waypointnda/waypointnda.com#3]
Should Waypoint include a special exception for disclosure to the Serious Fraud Office under Bribery Act 2010?

**Comment by neilzone** [comment]
Given s4(h) is broad, I do not see a reason for a specific reference here.

However, it might be worth amending 4(b) to ensure that it is not a breach of contract to make a disclosure which is required by law, provided that any such disclosure is made in accordance with 4(h)?

**Comment by kemitchell** [comment]
@neilzone Thanks!

**Comment by kemitchell** [comment]
@neilzone, I've slated to address this in 2.0.0. The revised language:

> (a)	Nondisclosure. Except as described in Section 4(b) (Permitted Disclosure) <ins>or as required by law</ins>, Receiving Party shall not disclose Confidential Information to anyone.
